version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - '8090:80'
    volumes:
      - ./dist:/usr/share/nginx/html
      # 未修复前的报错复现
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # 修复后的CSP策略
      - ./nginx-fixed.conf:/etc/nginx/conf.d/default.conf
    restart: always
