version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - '8090:80'
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
