import Head from 'next/head'
import styles from '@/styles/About.module.css'

interface PostsItem {
  userId: number
  id: number
  title: string
  body: string
}

// SSG的静态生成:  页面内容取决于外部数据
export async function getStaticProps<T>(): Promise<{
  props: { posts: T[] }
}> {
  const res = await fetch('https://jsonplaceholder.typicode.com/posts')
  const posts = await res.json()

  // 通过返回 { props: { posts } } 对象，Blog 组件
  // 在构建时将接收到 `posts` 参数
  return {
    props: {
      posts
    }
  }
}

export async function getStaticPaths() {
  const res = await fetch('https://jsonplaceholder.typicode.com/posts')
  const posts: PostsItem[] = await res.json()

  // 据博文列表生成所有需要预渲染的路径
  const paths = posts.map((p) => ({ params: { id: p.id } }))
  // { fallback: false } means other routes should 404.
  return {
    paths,
    fallback: false
  }
}



export default function About<T extends PostsItem>({ posts }: { posts: T[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className={styles.about}>
          <h1>About</h1>
          <ul>
            {posts.map((post) => (
              <li key={post.id}>
                {post.id}. {post.title}
              </li>
            ))}
          </ul>
        </main>
      </div>
    </>
  )
}
