// ==UserScript==
// @name         全量加载页面所有懒资源
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       Lorain
// @match        *://mp.weixin.qq.com/s*
// @match        *://www.zhihu.com/market/paid_column/*
// @require      https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js
// @grant        none
// ==/UserScript==

(function () {
    'use strict';
    $(function () {
        const main = (() => {
            const button = `
            <div class="loadingio-spinner-wedges-ke0ejj3wr7p" id="___control_btn">
                <div class="ldio-2jhc8274vnn" id="btn">
                    <div>
                        <div><div></div></div><div><div></div></div><div><div></div></div><div><div></div></div>
                    </div>
                </div>
            </div>
            <style type="text/css">
                @keyframes ldio-2jhc8274vnn {
                    0% {
                        transform: rotate(0deg)
                    }

                    100% {
                        transform: rotate(360deg)
                    }
                }

                .ldio-2jhc8274vnn>div>div {
                    transform-origin: 100px 100px;
                    animation: ldio-2jhc8274vnn 3.0303030303030303s linear infinite;
                    opacity: 0.8
                }

                .ldio-2jhc8274vnn>div>div>div {
                    position: absolute;
                    left: 30px;
                    top: 30px;
                    width: 70px;
                    height: 70px;
                    border-radius: 70px 0 0 0;
                    transform-origin: 100px 100px
                }

                .ldio-2jhc8274vnn>div div:nth-child(1) {
                    animation-duration: 0.7575757575757576s
                }

                .ldio-2jhc8274vnn>div div:nth-child(1)>div {
                    background: #e15b64;
                    transform: rotate(0deg);
                }

                .ldio-2jhc8274vnn>div div:nth-child(2) {
                    animation-duration: 1.0101010101010102s
                }

                .ldio-2jhc8274vnn>div div:nth-child(2)>div {
                    background: #f47e60;
                    transform: rotate(0deg);
                }

                .ldio-2jhc8274vnn>div div:nth-child(3) {
                    animation-duration: 1.5151515151515151s
                }

                .ldio-2jhc8274vnn>div div:nth-child(3)>div {
                    background: #f8b26a;
                    transform: rotate(0deg);
                }

                .ldio-2jhc8274vnn>div div:nth-child(4) {
                    animation-duration: 3.0303030303030303s
                }

                .ldio-2jhc8274vnn>div div:nth-child(4)>div {
                    background: #abbd81;
                    transform: rotate(0deg);
                }

                .loadingio-spinner-wedges-ke0ejj3wr7p {
                    width: 200px;
                    height: 200px;
                    display: inline-block;
                    overflow: hidden;
                    background: #ffffff;
                    transform: scale(0.2);
                    position: fixed;
                    top: -70px;
                    right: -70px;
                    cursor: pointer;
                }

                .ldio-2jhc8274vnn {
                    width: 100%;
                    height: 100%;
                    position: relative;
                    transform: translateZ(0) scale(1);
                    backface-visibility: hidden;
                    transform-origin: 0 0;
                    /* see note above */
                }

                .ldio-2jhc8274vnn div {
                    box-sizing: content-box;
                }

                #bottomToolBar,
                [class*=ShelfTopNav-root]{
                    display:none;
                }

                /* generated by https://loading.io/ */
            </style>`
            $(document.body).append(button);
            $('#___control_btn').delegate('div#btn', 'click', function () {
                (function loadAll() {
                    const vh = document.documentElement.clientHeight;
                    window.scrollTo(0, document.documentElement.scrollTop + vh);
                    if (document.documentElement.scrollTop + document.documentElement.clientHeight >= document.documentElement.scrollHeight) {
                        console.log('触底确认中...')
                        setTimeout(()=>{
                            if (document.documentElement.scrollTop + document.documentElement.clientHeight >= document.documentElement.scrollHeight) {
                                window.print();
                                return;
                            }else{
                                setTimeout(loadAll, 1000);
                            }
                        },2000);
                    } else {
                        setTimeout(loadAll, 1000);
                    }
                })()
            })
        })()
    });
    // Your code here...
})();